/** First-party Agent Skills shipped with the platform service. */
export const BUNDLED_SKILL_NAMES = [
  'game-development',
  'game-code-review',
  'unreal-development',
  'unity-development',
  'godot-scene-audit',
  'engine-integration-tests',
  'gameplay-implementation',
  'test-driven-development',
  'asset-pipeline',
  'visual-consistency',
  'blender-modeling',
  'materials-textures',
  'rigging-animation',
  'sprite-production',
  'game-audio',
  'technical-art-vfx',
  'game-design-review',
  'level-design',
  'narrative-style-guide',
  'game-ai',
  'multiplayer-gameplay',
  'game-accessibility',
  'game-localization',
  'game-performance',
  'game-build-release',
  'project-planning',
  'evidence-review',
  'source-research',
  'discussion-board-maintenance',
  'security-review',
] as const;
