import { homedir } from 'node:os';
import path from 'node:path';
import type { SettingDefinition, SettingGroup, SideEffect } from '@gamecrafter/contracts';

export interface BuiltinSettings {
  groups: SettingGroup[];
  definitions: SettingDefinition[];
}

export function createBuiltinSettings(): BuiltinSettings {
  const groups: SettingGroup[] = [
    {
      id: 'general',
      title: 'General & background behaviour',
      description: 'General settings for the Control Room and background service.',
      order: 0,
    },
    {
      id: 'projects',
      title: 'Projects, genres & modules',
      description: 'Project creation and organization defaults.',
      order: 1,
    },
    {
      id: 'agents',
      title: 'Agents, swarms & skills',
      description: 'Agent delegation and skill behavior.',
      order: 2,
    },
    {
      id: 'models',
      title: 'Model providers & routing',
      description: 'Model selection and task budgets.',
      order: 3,
    },
    {
      id: 'connections',
      title: 'Engine, asset & tool connections',
      description: 'Connections to game engines, asset services, and tools.',
      order: 4,
    },
    {
      id: 'access',
      title: 'Access & security',
      description: 'Access controls and security policies.',
      order: 5,
    },
    {
      id: 'board',
      title: 'Discussion board',
      description:
        'Discussion board behavior and maintenance routed through the board-maintainer model pool.',
      order: 6,
    },
    {
      id: 'plugins',
      title: 'Plugins & updates',
      description: 'Platform plugin installation and update behavior.',
      order: 7,
    },
    {
      id: 'storage',
      title: 'Storage, search & backup',
      description: 'Search indexes, backup, and storage behavior.',
      order: 8,
    },
    {
      id: 'logs',
      title: 'Logs & audit',
      description: 'Logging and audit retention.',
      order: 9,
    },
  ];
  const definitions: SettingDefinition[] = [
    setting(
      'window.closeBehavior',
      'Window close behavior',
      'Choose whether closing the window leaves work running or stops after checkpointing.',
      'general',
      { type: 'string', enum: ['continue', 'stop-and-checkpoint'] },
      'continue',
      ['platform'],
    ),
    setting(
      'projects.defaultParentDirectory',
      'Default Project parent directory',
      'Default directory used when creating Projects.',
      'projects',
      { type: 'string' },
      path.join(homedir(), 'GameCrafterProjects'),
      ['platform'],
    ),
    setting(
      'agents.maxSpawnDepth',
      'Maximum agent spawn depth',
      'Maximum number of nested agent delegation levels.',
      'agents',
      { type: 'integer', minimum: 1, maximum: 16 },
      4,
      ['platform', 'project'],
    ),
    setting(
      'agents.maxConcurrentPerProject',
      'Maximum concurrent agents per Project',
      'Maximum number of agents that can work concurrently on one Project.',
      'agents',
      { type: 'integer', minimum: 1, maximum: 64 },
      8,
      ['platform', 'project'],
    ),
    setting(
      'access.mode',
      'Access mode',
      'Controls how tool operations are authorized.',
      'access',
      { type: 'string', enum: ['full', 'restricted', 'ask-always'] },
      'ask-always',
      ['platform', 'project', 'session'],
    ),
    setting(
      'access.restricted.allowedSideEffects',
      'Allowed restricted-mode side effects',
      'Side-effect categories permitted without an explicit tool allowlist.',
      'access',
      {
        type: 'array',
        items: {
          type: 'string',
          enum: [
            'none',
            'internal-write',
            'workspace-write',
            'external-write',
            'paid',
            'destructive',
          ],
        },
        uniqueItems: true,
      },
      ['none', 'internal-write', 'workspace-write'] as SideEffect[],
      ['platform', 'project'],
    ),
    setting(
      'access.restricted.allowedTools',
      'Allowed restricted-mode tools',
      'Tool ID globs permitted while access is restricted.',
      'access',
      { type: 'array', items: { type: 'string' }, uniqueItems: true },
      [],
      ['platform', 'project'],
    ),
    setting(
      'access.askAlways.approvalTimeoutMinutes',
      'Approval timeout (minutes)',
      'How long approval requests remain pending.',
      'access',
      { type: 'integer', minimum: 1 },
      30,
      ['platform', 'project', 'session'],
    ),
    setting(
      'models.autoRouting.quality',
      'Automatic routing quality policy',
      'Select the quality, balance, or cost priority for automatic model routing.',
      'models',
      { type: 'string', enum: ['quality-first', 'balanced', 'cost-first'] },
      'quality-first',
      ['platform', 'project', 'session'],
    ),
    setting(
      'models.autoRouting.maxLatencyMs',
      'Maximum routing latency (ms)',
      'Set zero for no maximum latency constraint.',
      'models',
      { type: 'integer', minimum: 0 },
      0,
      ['platform', 'project', 'session'],
    ),
    setting(
      'models.exploration.rate',
      'Model exploration rate',
      'Probability of exploring a less-observed eligible model.',
      'models',
      { type: 'number', minimum: 0, maximum: 1 },
      0.1,
      ['platform', 'project'],
    ),
    setting(
      'models.exploration.budgetUsdPerDay',
      'Daily model exploration budget (USD)',
      'Maximum daily spend on exploration picks.',
      'models',
      { type: 'number', minimum: 0 },
      1,
      ['platform', 'project'],
    ),
    setting(
      'models.budget.maxCostPerTaskUsd',
      'Maximum cost per task (USD)',
      'Maximum model spend allowed for a single task.',
      'models',
      { type: 'number', minimum: 0 },
      5,
      ['platform', 'project', 'session'],
    ),
    setting(
      'skills.catalog.maxEntries',
      'Maximum skill catalog entries',
      'Maximum number of eligible skills shown before search is needed.',
      'agents',
      { type: 'integer', minimum: 5 },
      40,
      ['platform', 'project'],
    ),
    setting(
      'skills.compatibilityScan.enabled',
      'Scan compatible skill directories',
      'Offer skills discovered in compatible agent-tool directories for trusted Projects.',
      'agents',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'skills.installLimits.archiveMiB',
      'Maximum skill archive size (MiB)',
      'Maximum compressed archive size accepted by the skill installer.',
      'plugins',
      { type: 'integer' },
      10,
      ['platform'],
    ),
    setting(
      'skills.installLimits.extractedMiB',
      'Maximum extracted skill size (MiB)',
      'Maximum total extracted size accepted by the skill installer.',
      'plugins',
      { type: 'integer' },
      25,
      ['platform'],
    ),
    setting(
      'skills.installLimits.maxFiles',
      'Maximum files in a skill archive',
      'Maximum number of files extracted by the skill installer.',
      'plugins',
      { type: 'integer' },
      1000,
      ['platform'],
    ),
    setting(
      'mcp.autoConnect',
      'Connect enabled MCP servers automatically',
      'Automatically connect enabled platform and Project MCP connections.',
      'connections',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'mcp.reconnectBackoffSeconds',
      'MCP reconnection backoff (seconds)',
      'Delay before retrying a disconnected MCP connection.',
      'connections',
      { type: 'integer' },
      10,
      ['platform'],
    ),
    setting(
      'board.auditIntervalMinutes',
      'Board audit interval (minutes)',
      'Interval for the board-maintainer model pool to audit open threads and decisions.',
      'board',
      { type: 'integer', minimum: 1 },
      240,
      ['platform', 'project'],
    ),
    setting(
      'board.archiveAfterDays',
      'Archive resolved threads after (days)',
      'Age after which resolved threads are summarized and archived with their history retained.',
      'board',
      { type: 'integer', minimum: 1 },
      30,
      ['platform', 'project'],
    ),
    setting(
      'board.auditMinMessages',
      'Minimum thread messages for audit',
      'Only open threads with at least this many messages are sent for maintenance audit.',
      'board',
      { type: 'integer', minimum: 1 },
      5,
      ['platform', 'project'],
    ),
    setting(
      'board.maxSyncAttempts',
      'Maximum decision sync attempts',
      'Maximum automatic retries for a binding decision canon synchronization.',
      'board',
      { type: 'integer', minimum: 1 },
      5,
      ['platform', 'project'],
    ),
    setting(
      'board.allowPermanentDeletion',
      'Allow permanent board deletion',
      'Allow permanent thread deletion; otherwise board history may only be archived.',
      'board',
      { type: 'boolean' },
      false,
      ['platform', 'project'],
    ),
    setting(
      'board.maintenanceEnabled',
      'Enable board maintenance',
      'Enable scheduled board-maintainer audits and archive cleanup.',
      'board',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'search.vector.enabled',
      'Enable semantic vector search',
      'Enable the configured vector-store adapter for semantic retrieval.',
      'storage',
      { type: 'boolean' },
      false,
      ['platform', 'project'],
    ),
    setting(
      'backup.encryption.enabled',
      'Encrypt backups',
      'Encrypted by default; disabling is not recommended.',
      'storage',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'logs.retentionDays',
      'Log retention (days)',
      'Number of days to retain service logs.',
      'logs',
      { type: 'integer', minimum: 1 },
      30,
      ['platform'],
    ),
  ];

  return { groups, definitions };
}

function setting(
  key: string,
  title: string,
  description: string,
  group: string,
  schema: Record<string, unknown>,
  defaultValue: unknown,
  scopes: SettingDefinition['scopes'],
): SettingDefinition {
  return {
    key,
    title,
    description,
    group,
    schema,
    default: defaultValue,
    scopes,
    source: 'builtin',
  };
}
